p1:pipe1.c
	gcc -o $@ $^ 


.PHONY:all
all1:p2

p2:pipe2.c
	gcc -o $@ $^



.PHONY:all2
all2:p3

p3:pipe3.c
	gcc -o $@ $^


.PHONY:all3
all3:p4

p4:pipe4.c
	gcc -o $@ $^



.PHONY:clean
clean:
	rm -f p1 p2 p3
